name: num_utilities
description: >-
  A collection of extension methods for nums, ints, and doubles;
  and iterables of nums, ints, and doubles.
version: 1.0.1
homepage: https://github.com/james-alex/num_utilities

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
